### ISSUE TITLE
 New rule: Fail if test has no assertions

### ISSUE THREAD

**Issue by arunvelsriram** [arunvelsriram/ktlint-ruleset-junit#3]

**Comment by DeMack** [comment]
PR: https://github.com/arunvelsriram/ktlint-ruleset-junit/pull/6

**Comment by arunvelsriram** [comment]
Readme needs to be updated

**Comment by DeMack** [comment]
Given that at the end of the current issues, there will only be three rules, it's not a huge issue, but assuming that this will eventually become a fully-fledged library, having all the rules individually in the initial `README` will get unwieldy and intimidating for a new user. If you'd like, I can set up a second doc that will serve to house all the details and just link to each one in the `README`. It's definitely not a huge deal for just three rules, so I'm good either way.

Another thought is that it might not be a bad idea to migrate the rule details to a wiki.

**Comment by DeMack** [comment]
PR for `README` update: https://github.com/arunvelsriram/ktlint-ruleset-junit/pull/7

**Comment by arunvelsriram** [comment]
Yes, agree that readme is not the right place for all the rules. 

Let's wait for some time and once we start to see it grow we shall bring in a wiki/doc. What do you think?

**Comment by DeMack** [comment]
I think that sounds perfect. The PR should be good to merge, then.

**Comment by arunvelsriram** [comment]
What's your thought on using a table for the current readme? We could also simplify the example or provide examples only when required.

**Comment by DeMack** [comment]
I think a table would probably just get too cluttered. Since there are so few rules right now, it's fairly easy to see everything at a glance, so I don't think we should spend too much effort on organization just yet. 

That said, once it gets to 5+ a table could be useful to give a high level overview, with examples in the wiki.

**Comment by arunvelsriram** [comment]
Makes sense.
